#!/usr/bin/env python3
"""
Supabase Setup and Verification Script
Verifies environment variables and ensures bucket exists.
"""

import os
import sys
from dotenv import load_dotenv
from supabase_client import SupabaseClient

# Load environment variables
load_dotenv()

# Configuration
BUCKET_NAME = "rvtfiles"


def verify_environment():
    """Verify all required environment variables are present."""
    print("="*60)
    print("Environment Variable Verification")
    print("="*60)
    print()
    
    # Check for service key first, fall back to anon key
    supabase_key = os.getenv('SUPABASE_SERVICE_KEY') or os.getenv('SUPABASE_ANON_KEY')
    key_type = 'SUPABASE_SERVICE_KEY' if os.getenv('SUPABASE_SERVICE_KEY') else 'SUPABASE_ANON_KEY'
    
    required_vars = {
        'SUPABASE_URL': os.getenv('SUPABASE_URL'),
        key_type: supabase_key,
        'client_id': os.getenv('client_id'),
        'client_secret': os.getenv('client_secret')
    }
    
    all_present = True
    
    for var_name, var_value in required_vars.items():
        if var_value:
            # Mask sensitive values
            if 'KEY' in var_name or 'SECRET' in var_name or 'client_secret' in var_name:
                display_value = f"{var_value[:8]}...{var_value[-4:]}" if len(var_value) > 12 else "***"
            else:
                display_value = var_value
            print(f"✓ {var_name}: {display_value}")
        else:
            print(f"✗ {var_name}: NOT FOUND")
            all_present = False
    
    print()
    
    # Warn if using anon key instead of service key
    if os.getenv('SUPABASE_ANON_KEY') and not os.getenv('SUPABASE_SERVICE_KEY'):
        print("⚠️  WARNING: Using SUPABASE_ANON_KEY instead of SUPABASE_SERVICE_KEY")
        print("   Service key is recommended for full storage permissions (bucket creation, uploads).")
        print("   Anon key may have limited permissions depending on your Supabase RLS policies.")
        print()
    
    if not all_present:
        print("ERROR: Missing required environment variables!")
        print("Please ensure your .env file contains:")
        print("  SUPABASE_URL=https://xxxx.supabase.co")
        print("  SUPABASE_SERVICE_KEY=xxxxxx  (preferred)")
        print("  OR SUPABASE_ANON_KEY=xxxxxx  (fallback, may have limited permissions)")
        print("  client_id=xxxx")
        print("  client_secret=xxxx")
        return False
    
    print("✓ All environment variables are present")
    print()
    return True


def verify_supabase_connection():
    """Verify Supabase connection and bucket."""
    print("="*60)
    print("Supabase Connection Verification")
    print("="*60)
    print()
    
    supabase_url = os.getenv('SUPABASE_URL')
    # Try service key first, fall back to anon key
    supabase_key = os.getenv('SUPABASE_SERVICE_KEY') or os.getenv('SUPABASE_ANON_KEY')
    
    if not supabase_url or not supabase_key:
        print("ERROR: Cannot verify Supabase connection - missing credentials")
        return False
    
    try:
        # Initialize client
        print(f"Connecting to Supabase: {supabase_url}")
        client = SupabaseClient(supabase_url, supabase_key)
        
        # Check bucket
        print(f"\nChecking bucket '{BUCKET_NAME}'...")
        if client.bucket_exists(BUCKET_NAME):
            print(f"✓ Bucket '{BUCKET_NAME}' exists")
        else:
            print(f"✗ Bucket '{BUCKET_NAME}' does not exist")
            print(f"\nCreating bucket '{BUCKET_NAME}'...")
            success, message = client.create_bucket(BUCKET_NAME, public=False)
            if success:
                print(f"✓ {message}")
            else:
                print(f"✗ {message}")
                return False
        
        print()
        print("✓ Supabase connection verified successfully")
        return True
        
    except Exception as e:
        print(f"✗ Error connecting to Supabase: {str(e)}")
        return False


def print_signed_url_instructions():
    """Print instructions for obtaining signed URLs."""
    print("="*60)
    print("Signed URL Information")
    print("="*60)
    print()
    print("Signed URLs are automatically generated by the pipeline.")
    print("They are valid for 2 hours (7200 seconds) from creation.")
    print()
    print("To manually create a signed URL via REST API:")
    print()
    print("1. Upload a file to the bucket first:")
    print("   POST {SUPABASE_URL}/storage/v1/object/{bucket}/{object_name}")
    print("   Headers: Authorization: Bearer {SERVICE_KEY}")
    print()
    print("2. Create signed URL:")
    print("   POST {SUPABASE_URL}/storage/v1/object/sign/{bucket}/{object_name}")
    print("   Headers: Authorization: Bearer {SERVICE_KEY}")
    print("   Body: {\"expiresIn\": 7200}")
    print()
    print("3. The response will contain a 'signedURL' field.")
    print("   Full URL = {SUPABASE_URL} + signedURL")
    print()
    print("The convert_all_rvt.py script handles this automatically.")
    print()


def main():
    """Main setup function."""
    print()
    print("="*60)
    print("Supabase Setup and Verification")
    print("="*60)
    print()
    
    # Step 1: Verify environment variables
    if not verify_environment():
        sys.exit(1)
    
    # Step 2: Verify Supabase connection and bucket
    if not verify_supabase_connection():
        print("\nERROR: Supabase setup failed!")
        sys.exit(1)
    
    # Step 3: Print signed URL instructions
    print_signed_url_instructions()
    
    print("="*60)
    print("Setup Complete!")
    print("="*60)
    print()
    print("You can now run the conversion pipeline:")
    print("  python convert_all_rvt.py")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nFATAL ERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

